/**
 * GENERATED by `pnpm build:content` — do not edit.
 *
 * Packs, works and edition headers. No segment text: that lives in
 * `public/content/editions/` and is fetched per edition, so the bundle does
 * not grow with the corpus.
 */
import type { ContentPack, Shelf, Work } from "../types";

export const CONTENT_PACKS: ContentPack[] = [
  {
    "id": "hamsun-markens-groede",
    "title": "Knut Hamsun: Markens grøde",
    "description": "Langform, naturprosa og vedvarende rytme. V1 rommer åpningen av første del, kapittel I (1917).",
    "languageProfileIds": [
      "brand-riksmaal"
    ],
    "workIds": [
      "hamsun-markens-groede"
    ],
    "tags": [
      "prosa",
      "roman",
      "1900-tallet"
    ],
    "status": "active",
    "sourceAttribution": [
      {
        "author": "Knut Hamsun",
        "title": "Markens Grøde",
        "publishedYear": 1917,
        "language": "da-NO",
        "sourceUrl": "https://no.wikisource.org/wiki/Markens_Gr%C3%B8de/1/01",
        "archiveId": "wikikilden:Markens_Grøde/1/01",
        "retrievedAt": "2026-09-04",
        "provider": "Wikikilden (no.wikisource.org)",
        "authorDeathYear": 1952,
        "license": "Public domain i Norge (Hamsun d. 1952; verkets vernetid utløp 2023-01-01, life+70) og i USA (utgitt 1917, før 1928-grensen). Wikikildens transkripsjon er en tro gjengivelse av en offentlig tekst og tilbys under CC BY-SA 4.0; attribusjon til Wikikilden er beholdt her.",
        "rightsStatus": "public-domain",
        "digitalEdition": "Markens Grøde. Kristiania: Gyldendal, 1917. Første del, kapittel I (transkribert etter Internet Archive-skanningen markensgrde01hams).",
        "verificationStatus": "agent-drafted",
        "editorialNotes": [
          "Rå HTML arkivert under source/wikikilden/markens-groede-1-01.html; ekstrahert tekst i source/markens-groede-1-01.txt."
        ]
      }
    ]
  },
  {
    "id": "hamsun-sult",
    "title": "Knut Hamsun: Sult",
    "description": "Firedelt sultroman i naturalistisk jeg-form. V1 rommer hele verket, bygget i fire ekte moduler (Første–Fjerde Stykke) — den første pakken i katalogen med reell modulstruktur.",
    "languageProfileIds": [
      "brand-riksmaal"
    ],
    "workIds": [
      "hamsun-sult"
    ],
    "tags": [
      "prosa",
      "roman",
      "1800-tallet"
    ],
    "status": "active",
    "sourceAttribution": [
      {
        "author": "Knut Hamsun",
        "title": "Sult",
        "publishedYear": 1890,
        "language": "da-NO",
        "sourceUrl": "https://no.wikisource.org/wiki/Sult",
        "archiveId": "wikikilden:Sult/01–04",
        "retrievedAt": "2026-09-10",
        "provider": "Wikikilden (no.wikisource.org)",
        "authorDeathYear": 1952,
        "license": "Public domain i Norge (Hamsun d. 1952; verkets vernetid utløp 2023-01-01, life+70) og i USA (utgitt 1890). Wikikildens transkripsjon er en tro gjengivelse av en offentlig tekst og tilbys under CC BY-SA 4.0; attribusjon til Wikikilden er beholdt her.",
        "rightsStatus": "public-domain",
        "digitalEdition": "Sult. København: P. G. Philipsens Forlag, 1890. Førsteutgaven, i sin helhet: Første, Andet, Tredje og Fjerde Stykke. Transkribert etter Wikikildens skannede utgave (Indeks:Sult (Knut Hamsun).djvu, Fremgang V — validert, 345 sider; trykt side 1 = djvu-side 13).",
        "verificationStatus": "agent-drafted",
        "editorialNotes": [
          "Rå HTML arkivert under source/wikikilden/sult-01.html til sult-04.html; ekstrahert tekst i source/sult-01.txt til sult-04.txt.",
          "Sidene ligger på Wikikilden under Sult/01–Sult/04. Det finnes en foreldreløs duplikattre under Sult/Sult/01–04 på samme wiki — den er ikke kilden og skal ikke brukes."
        ]
      }
    ]
  },
  {
    "id": "ibsen-brand",
    "title": "Henrik Ibsen: Brand",
    "description": "Produktets navngivende kjernetekst. Et dramatisk dikt i fem akter (1866); V1 rommer åpningsscenen i første akt.",
    "languageProfileIds": [
      "brand-riksmaal"
    ],
    "workIds": [
      "ibsen-brand"
    ],
    "tags": [
      "drama",
      "vers",
      "1800-tallet"
    ],
    "status": "active",
    "sourceAttribution": [
      {
        "author": "Henrik Ibsen",
        "title": "Brand. Et dramatisk digt",
        "publishedYear": 1866,
        "language": "da-NO",
        "sourceUrl": "https://runeberg.org/brand/",
        "archiveId": "runeberg:brand",
        "retrievedAt": "2026-09-04",
        "provider": "Project Runeberg",
        "authorDeathYear": 1906,
        "license": "Public domain (Ibsen d. 1906; edition printed 1903). Transcription proofread at least once on Project Runeberg.",
        "rightsStatus": "public-domain",
        "digitalEdition": "Brand. Et dramatisk digt. Femtende oplag. København: Gyldendalske Boghandels Forlag (F. Hegel & Søn), 1903. Scanned and OCR-transcribed by Project Runeberg.",
        "verificationStatus": "agent-drafted",
        "editorialNotes": [
          "Pages 3–14 archived under source/runeberg/; extracted text in source/runeberg-brand-0003-0014.txt.",
          "Cross-reference: Henrik Ibsens skrifter (ibsen.uio.no, CC BY-NC 4.0) for the 1866 first-edition text."
        ]
      }
    ]
  },
  {
    "id": "kielland-gift",
    "title": "Alexander Kielland: Gift",
    "description": "Samfunnskritisk roman med variert dialog og fortellende prosa. V1 rommer åpningen av kapittel I (1883/1907-teksten).",
    "languageProfileIds": [
      "brand-riksmaal"
    ],
    "workIds": [
      "kielland-gift"
    ],
    "tags": [
      "prosa",
      "roman",
      "1800-tallet",
      "dialog"
    ],
    "status": "active",
    "sourceAttribution": [
      {
        "author": "Alexander L. Kielland",
        "title": "Gift",
        "publishedYear": 1883,
        "language": "da-NO",
        "sourceUrl": "https://no.wikisource.org/wiki/Gift/1",
        "archiveId": "wikikilden:Gift/1",
        "retrievedAt": "2026-09-04",
        "provider": "Wikikilden (no.wikisource.org)",
        "authorDeathYear": 1906,
        "license": "Public domain (Kielland d. 1906; verkets vernetid er utløpt, life+70). Wikikildens transkripsjon er en tro gjengivelse av en offentlig tekst og tilbys under CC BY-SA 4.0; attribusjon til Wikikilden er beholdt her.",
        "rightsStatus": "public-domain",
        "digitalEdition": "Samlede Værker, Andet Bind. Kristiania: Gyldendalske Boghandel Nordisk Forlag, 1907. Gift, kapittel I (trykte sider 165–171).",
        "verificationStatus": "agent-drafted",
        "editorialNotes": [
          "Rå HTML arkivert under source/wikikilden/gift-1.html; ekstrahert tekst i source/gift-1.txt."
        ]
      }
    ]
  },
  {
    "id": "kielland-noveletter",
    "title": "Alexander Kielland: Noveletter",
    "description": "Korte, selvstendige økter. V1 rommer åpningen av to noveller fra samlingen Noveletter (1879): «Haabet er lysegrønt» og «Visne Blade».",
    "languageProfileIds": [
      "brand-riksmaal"
    ],
    "workIds": [
      "kielland-noveletter"
    ],
    "tags": [
      "prosa",
      "novelle",
      "1800-tallet"
    ],
    "status": "active",
    "sourceAttribution": [
      {
        "author": "Alexander L. Kielland",
        "title": "Haabet er lysegrønt",
        "publishedYear": 1879,
        "language": "da-NO",
        "sourceUrl": "https://no.wikisource.org/wiki/Haabet_er_lysegr%C3%B8nt",
        "archiveId": "wikikilden:Haabet_er_lysegrønt",
        "retrievedAt": "2026-09-04",
        "provider": "Wikikilden (no.wikisource.org)",
        "authorDeathYear": 1906,
        "license": "Public domain (Kielland d. 1906; verkets vernetid er utløpt, life+70). Wikikildens transkripsjon er en tro gjengivelse av en offentlig tekst og tilbys under CC BY-SA 4.0; attribusjon til Wikikilden er beholdt her.",
        "rightsStatus": "public-domain",
        "digitalEdition": "Samlede Værker, Første Bind. Kristiania: Gyldendalske Boghandel Nordisk Forlag, 1907. «Haabet er lysegrønt» (trykte sider 7–13).",
        "verificationStatus": "agent-drafted",
        "editorialNotes": [
          "Rå HTML arkivert under source/wikikilden/haabet-er-lysegroent.html."
        ]
      },
      {
        "author": "Alexander L. Kielland",
        "title": "Visne Blade",
        "publishedYear": 1879,
        "language": "da-NO",
        "sourceUrl": "https://no.wikisource.org/wiki/Visne_Blade",
        "archiveId": "wikikilden:Visne_Blade",
        "retrievedAt": "2026-09-04",
        "provider": "Wikikilden (no.wikisource.org)",
        "authorDeathYear": 1906,
        "license": "Public domain (Kielland d. 1906; verkets vernetid er utløpt, life+70). Wikikildens transkripsjon er en tro gjengivelse av en offentlig tekst og tilbys under CC BY-SA 4.0; attribusjon til Wikikilden er beholdt her.",
        "rightsStatus": "public-domain",
        "digitalEdition": "Samlede Værker, Første Bind. Kristiania: Gyldendalske Boghandel Nordisk Forlag, 1907. «Visne Blade» (trykte sider 13–16).",
        "verificationStatus": "agent-drafted",
        "editorialNotes": [
          "Rå HTML arkivert under source/wikikilden/visne-blade.html.",
          "Samlingens prioriterte tekst, «Balstemning», er ennå ikke i pakken, men finnes korrekturlest på Wikikilden under 1907-utgavens stavemåte med én L (https://no.wikisource.org/wiki/Balstemning). Den tidligere merknaden her sa at ingen fri kilde var funnet; feilen lå i søkestrengen, ikke i kilden. Se docs/CORPUS_STATUS.md."
        ]
      }
    ]
  }
];

export const WORKS: Work[] = [
  {
    "id": "hamsun-markens-groede",
    "contentPackId": "hamsun-markens-groede",
    "author": "Knut Hamsun",
    "title": "Markens grøde",
    "publishedYear": 1917,
    "originalLanguage": "da-NO",
    "source": {
      "author": "Knut Hamsun",
      "title": "Markens Grøde",
      "publishedYear": 1917,
      "language": "da-NO",
      "sourceUrl": "https://no.wikisource.org/wiki/Markens_Gr%C3%B8de/1/01",
      "archiveId": "wikikilden:Markens_Grøde/1/01",
      "retrievedAt": "2026-09-04",
      "provider": "Wikikilden (no.wikisource.org)",
      "authorDeathYear": 1952,
      "license": "Public domain i Norge (Hamsun d. 1952; verkets vernetid utløp 2023-01-01, life+70) og i USA (utgitt 1917, før 1928-grensen). Wikikildens transkripsjon er en tro gjengivelse av en offentlig tekst og tilbys under CC BY-SA 4.0; attribusjon til Wikikilden er beholdt her.",
      "rightsStatus": "public-domain",
      "digitalEdition": "Markens Grøde. Kristiania: Gyldendal, 1917. Første del, kapittel I (transkribert etter Internet Archive-skanningen markensgrde01hams; Wikikilden-siden Markens_Grøde/1/01 transkluderer sidene 5–15 i skannet bok / trykte sider 11–21).",
      "verificationStatus": "agent-drafted",
      "editorialNotes": [
        "Rå HTML arkivert under source/wikikilden/markens-groede-1-01.html; ekstrahert tekst i source/markens-groede-1-01.txt.",
        "Kapitteloverskriften «I» er ikke tatt med som segment; utdraget starter på kapitlets første prosalinje («Den lange, lange Sti …»)."
      ]
    },
    "editions": [
      {
        "id": "hamsun-markens-groede.original",
        "workId": "hamsun-markens-groede",
        "kind": "original",
        "version": "1.0.0",
        "contentHash": "sha256:db67765fc4831f1266973af04debf38a2ea64493a0b6f430d0a9391a0eb572a2",
        "adaptationStatus": "none",
        "segmentCount": 8,
        "wordCount": 813,
        "file": "/content/editions/hamsun-markens-groede.original.db67765fc483.json"
      },
      {
        "id": "hamsun-markens-groede.training.v1",
        "workId": "hamsun-markens-groede",
        "kind": "training-edition",
        "version": "1.0.0",
        "contentHash": "sha256:1d8c5519a5afbf1ddee33976cf063627f34f76b2ba12a6a7b33fc0cb52cf69d5",
        "languageProfileId": "brand-riksmaal",
        "adaptationStatus": "orthography",
        "basedOnEditionId": "hamsun-markens-groede.original",
        "basedOnContentHash": "sha256:db67765fc4831f1266973af04debf38a2ea64493a0b6f430d0a9391a0eb572a2",
        "segmentCount": 8,
        "wordCount": 813,
        "file": "/content/editions/hamsun-markens-groede.training.v1.1d8c5519a5af.json"
      },
      {
        "id": "hamsun-markens-groede.training.v2",
        "workId": "hamsun-markens-groede",
        "kind": "training-edition",
        "version": "2.0.0",
        "contentHash": "sha256:c23ab5fa6b0d3ca804f158be24466e4385e28657041b9b15edc3aeaeefb24b66",
        "languageProfileId": "brand-riksmaal",
        "adaptationStatus": "orthography",
        "basedOnEditionId": "hamsun-markens-groede.original",
        "basedOnContentHash": "sha256:db67765fc4831f1266973af04debf38a2ea64493a0b6f430d0a9391a0eb572a2",
        "segmentCount": 8,
        "wordCount": 813,
        "file": "/content/editions/hamsun-markens-groede.training.v2.c23ab5fa6b0d.json"
      }
    ]
  },
  {
    "id": "hamsun-sult",
    "contentPackId": "hamsun-sult",
    "author": "Knut Hamsun",
    "title": "Sult",
    "publishedYear": 1890,
    "originalLanguage": "da-NO",
    "source": {
      "author": "Knut Hamsun",
      "title": "Sult",
      "publishedYear": 1890,
      "language": "da-NO",
      "sourceUrl": "https://no.wikisource.org/wiki/Sult",
      "archiveId": "wikikilden:Sult/01-04",
      "retrievedAt": "2026-09-10",
      "provider": "Wikikilden (no.wikisource.org)",
      "authorDeathYear": 1952,
      "license": "Public domain i Norge (Hamsun d. 1952; verkets vernetid utløp 2023-01-01, life+70) og i USA (utgitt 1890, før 1928-grensen). Wikikildens transkripsjon er en tro gjengivelse av en offentlig tekst og tilbys under CC BY-SA 4.0; attribusjon til Wikikilden er beholdt her.",
      "rightsStatus": "public-domain",
      "digitalEdition": "Sult. København: P. G. Philipsens Forlag, 1890 (førsteutgaven). Hele romanen, alle fire stykker, transkribert etter «Indeks:Sult (Knut Hamsun).djvu» — 345 sider, trykt side 1 = djvu-side 13.",
      "verificationStatus": "agent-drafted",
      "editorialNotes": [
        "Indeksen er merket Fremgang=V (validert), Wikikildens høyeste korrekturnivå.",
        "Wikikilden har to sidetrær for dette verket: Sult/01–04 og Sult/Sult/01–04. Begge transkluderer samme djvu, men Sult/01–04 er det innholdsfortegnelsen på Sult-siden lenker til; Sult/Sult/* er en foreldreløs dublett. Sult/01–04 er brukt.",
        "Rå HTML arkivert under source/wikikilden/sult-0N.html; ekstrahert tekst i source/sult-0N.txt."
      ]
    },
    "editions": [
      {
        "id": "hamsun-sult.original",
        "workId": "hamsun-sult",
        "kind": "original",
        "version": "1.0.0",
        "contentHash": "sha256:62d0c22f588d2f456282a2ec46eb2a8242cc88156093411b11f9f2a0cd45a3d3",
        "adaptationStatus": "none",
        "modules": [
          {
            "id": "stykke-1",
            "title": "Første stykke",
            "order": 1
          },
          {
            "id": "stykke-2",
            "title": "Andet stykke",
            "order": 2
          },
          {
            "id": "stykke-3",
            "title": "Tredje stykke",
            "order": 3
          },
          {
            "id": "stykke-4",
            "title": "Fjerde stykke",
            "order": 4
          }
        ],
        "segmentCount": 531,
        "wordCount": 60044,
        "file": "/content/editions/hamsun-sult.original.62d0c22f588d.json"
      }
    ]
  },
  {
    "id": "ibsen-brand",
    "contentPackId": "ibsen-brand",
    "author": "Henrik Ibsen",
    "title": "Brand",
    "publishedYear": 1866,
    "originalLanguage": "da-NO",
    "source": {
      "author": "Henrik Ibsen",
      "title": "Brand. Et dramatisk digt",
      "publishedYear": 1866,
      "language": "da-NO",
      "sourceUrl": "https://runeberg.org/brand/",
      "archiveId": "runeberg:brand",
      "retrievedAt": "2026-09-04",
      "provider": "Project Runeberg",
      "authorDeathYear": 1906,
      "license": "Public domain (Ibsen d. 1906; edition printed 1903). Transcription proofread at least once on Project Runeberg.",
      "rightsStatus": "public-domain",
      "digitalEdition": "Brand. Et dramatisk digt. Femtende oplag. København: Gyldendalske Boghandels Forlag (F. Hegel & Søn), 1903. Pages 7–14 (første akt, åpningen).",
      "verificationStatus": "agent-drafted",
      "editorialNotes": [
        "Transkripsjonen følger Runeberg-teksten ord for ord. Trykkets halvlinje-innrykk (verselinjer delt mellom replikker) er ikke gjengitt; hver replikkdel står på egen linje uten innrykk.",
        "Sidemarkører og blanke linjer fra skanningen er fjernet. Ingen språklige inngrep."
      ]
    },
    "editions": [
      {
        "id": "ibsen-brand.original",
        "workId": "ibsen-brand",
        "kind": "original",
        "version": "1.0.0",
        "contentHash": "sha256:dcca48d310d6dd50dddb91848ffaa169acb4f530d595f017e7198b7db953ac37",
        "adaptationStatus": "none",
        "segmentCount": 12,
        "wordCount": 931,
        "file": "/content/editions/ibsen-brand.original.dcca48d310d6.json"
      },
      {
        "id": "ibsen-brand.training.v1",
        "workId": "ibsen-brand",
        "kind": "training-edition",
        "version": "1.0.0",
        "contentHash": "sha256:92d613d9b1a385454935b2ce614de39fe1159a77a1569f67393a3cd18e3170e9",
        "languageProfileId": "brand-riksmaal",
        "adaptationStatus": "orthography",
        "basedOnEditionId": "ibsen-brand.original",
        "basedOnContentHash": "sha256:dcca48d310d6dd50dddb91848ffaa169acb4f530d595f017e7198b7db953ac37",
        "segmentCount": 12,
        "wordCount": 936,
        "file": "/content/editions/ibsen-brand.training.v1.92d613d9b1a3.json",
        "drills": {
          "id": "ibsen-brand.drills.v1",
          "contentHash": "sha256:1b9f950590f5aa4377f433689fd0c96ca6dad13bb5fc6bb9af84f528c069d007",
          "itemCount": 59,
          "file": "/content/editions/ibsen-brand.training.v1.drills.1b9f950590f5.json"
        }
      }
    ]
  },
  {
    "id": "kielland-gift",
    "contentPackId": "kielland-gift",
    "author": "Alexander L. Kielland",
    "title": "Gift",
    "publishedYear": 1883,
    "originalLanguage": "da-NO",
    "source": {
      "author": "Alexander L. Kielland",
      "title": "Gift",
      "publishedYear": 1883,
      "language": "da-NO",
      "sourceUrl": "https://no.wikisource.org/wiki/Gift/1",
      "archiveId": "wikikilden:Gift/1",
      "retrievedAt": "2026-09-04",
      "provider": "Wikikilden (no.wikisource.org)",
      "authorDeathYear": 1906,
      "license": "Public domain (Kielland d. 1906; verkets vernetid er utløpt, life+70). Wikikildens transkripsjon er en tro gjengivelse av en offentlig tekst og tilbys under CC BY-SA 4.0; attribusjon til Wikikilden er beholdt her. Wikikilden-siden merker kilden {{PD-old|nb}}.",
      "rightsStatus": "public-domain",
      "digitalEdition": "Samlede Værker, Andet Bind. Kristiania: Gyldendalske Boghandel Nordisk Forlag, 1907. Gift, kapittel I (trykte sider 165–171).",
      "verificationStatus": "agent-drafted",
      "editorialNotes": [
        "Rå HTML arkivert under source/wikikilden/gift-1.html; ekstrahert tekst i source/gift-1.txt.",
        "Gift ble første gang utgitt 1883; teksten her følger 1907-utgaven i Samlede Værker slik den er transkribert på Wikikilden."
      ]
    },
    "editions": [
      {
        "id": "kielland-gift.original",
        "workId": "kielland-gift",
        "kind": "original",
        "version": "1.0.0",
        "contentHash": "sha256:2dff6f05866e1f32ef3c4403a73bd9f268d580f90263c022607f294c2374bfa9",
        "adaptationStatus": "none",
        "segmentCount": 13,
        "wordCount": 855,
        "file": "/content/editions/kielland-gift.original.2dff6f05866e.json"
      },
      {
        "id": "kielland-gift.training.v1",
        "workId": "kielland-gift",
        "kind": "training-edition",
        "version": "1.0.0",
        "contentHash": "sha256:2365ad52a5d090f7c8460276810c68ba65f08329f84b3835bd7ae6d6e057772a",
        "languageProfileId": "brand-riksmaal",
        "adaptationStatus": "orthography",
        "basedOnEditionId": "kielland-gift.original",
        "basedOnContentHash": "sha256:2dff6f05866e1f32ef3c4403a73bd9f268d580f90263c022607f294c2374bfa9",
        "segmentCount": 13,
        "wordCount": 858,
        "file": "/content/editions/kielland-gift.training.v1.2365ad52a5d0.json"
      },
      {
        "id": "kielland-gift.training.v2",
        "workId": "kielland-gift",
        "kind": "training-edition",
        "version": "2.0.0",
        "contentHash": "sha256:39525fb2b5236758464bfe48a7a9df846f0eb76164dbd05849774329a95f3e4b",
        "languageProfileId": "brand-riksmaal",
        "adaptationStatus": "orthography",
        "basedOnEditionId": "kielland-gift.original",
        "basedOnContentHash": "sha256:2dff6f05866e1f32ef3c4403a73bd9f268d580f90263c022607f294c2374bfa9",
        "segmentCount": 13,
        "wordCount": 858,
        "file": "/content/editions/kielland-gift.training.v2.39525fb2b523.json"
      }
    ]
  },
  {
    "id": "kielland-noveletter",
    "contentPackId": "kielland-noveletter",
    "author": "Alexander L. Kielland",
    "title": "Noveletter",
    "publishedYear": 1879,
    "originalLanguage": "da-NO",
    "source": {
      "author": "Alexander L. Kielland",
      "title": "Noveletter",
      "publishedYear": 1879,
      "language": "da-NO",
      "sourceUrl": "https://no.wikisource.org/wiki/Novelletter",
      "archiveId": "wikikilden:Novelletter",
      "retrievedAt": "2026-09-04",
      "provider": "Wikikilden (no.wikisource.org)",
      "authorDeathYear": 1906,
      "license": "Public domain (Kielland d. 1906; verkets vernetid er utløpt, life+70). Wikikildens transkripsjon er en tro gjengivelse av en offentlig tekst og tilbys under CC BY-SA 4.0; attribusjon til Wikikilden er beholdt her.",
      "rightsStatus": "public-domain",
      "digitalEdition": "Samlede Værker, Første Bind. Kristiania: Gyldendalske Boghandel Nordisk Forlag, 1907. To noveller er brukt: «Haabet er lysegrønt» (trykte sider 7–13, Wikikilden-siden Haabet_er_lysegrønt) og «Visne Blade» (trykte sider 13–16, Wikikilden-siden Visne_Blade). Åpningen av hver novelle er tatt med.",
      "verificationStatus": "agent-drafted",
      "editorialNotes": [
        "Rå HTML arkivert under source/wikikilden/haabet-er-lysegroent.html og source/wikikilden/visne-blade.html; hver novelle er ekstrahert til sin egen .txt og deretter satt sammen til source/noveletter.txt (Haabet er lysegrønt først, så Visne Blade), fordi segments.json/build-original.ts bare støtter én sourceFile per pakke.",
        "«Balstemning», som er spesifikasjonens prioriterte novelle, er IKKE med i denne pakken ennå, men den finnes: 1907-utgaven staver tittelen med én L, og under den stavemåten er teksten fullt transkribert og korrekturlest på Wikikilden (https://no.wikisource.org/wiki/Balstemning, ~2 100 ord, samme bind som de to novellene her). En tidligere merknad på dette stedet sa at ingen fri kilde fantes; det var galt, og feilen lå i søkestrengen — alle søk brukte den moderne skrivemåten «Ballstemning» med to L-er. Rettet 2026-09-04 i docs/CORPUS_STATUS.md og 2026-09-08 her."
      ]
    },
    "editions": [
      {
        "id": "kielland-noveletter.original",
        "workId": "kielland-noveletter",
        "kind": "original",
        "version": "1.0.0",
        "contentHash": "sha256:b7d0ef61833c3045e4a5f36a5f46e89e5b867e2ecfe3a672b24d14c6d96a97b7",
        "adaptationStatus": "none",
        "segmentCount": 13,
        "wordCount": 851,
        "file": "/content/editions/kielland-noveletter.original.b7d0ef61833c.json"
      },
      {
        "id": "kielland-noveletter.original.v2",
        "workId": "kielland-noveletter",
        "kind": "original",
        "version": "2.0.0",
        "contentHash": "sha256:94b143e16d5cb3aa0ffd7c0efafc447327d4d46a05ae038ffaeac60c77b5f0cc",
        "adaptationStatus": "none",
        "segmentCount": 264,
        "wordCount": 25664,
        "file": "/content/editions/kielland-noveletter.original.v2.94b143e16d5c.json"
      },
      {
        "id": "kielland-noveletter.training.v1",
        "workId": "kielland-noveletter",
        "kind": "training-edition",
        "version": "1.0.0",
        "contentHash": "sha256:3fc4e8c12212d5e63a450cb13698574b6df43343bd8b01c08e377352113b64bc",
        "languageProfileId": "brand-riksmaal",
        "adaptationStatus": "orthography",
        "basedOnEditionId": "kielland-noveletter.original",
        "basedOnContentHash": "sha256:b7d0ef61833c3045e4a5f36a5f46e89e5b867e2ecfe3a672b24d14c6d96a97b7",
        "segmentCount": 13,
        "wordCount": 853,
        "file": "/content/editions/kielland-noveletter.training.v1.3fc4e8c12212.json"
      },
      {
        "id": "kielland-noveletter.training.v2",
        "workId": "kielland-noveletter",
        "kind": "training-edition",
        "version": "2.0.0",
        "contentHash": "sha256:e492070c9614c704b148c89561b2dc9a2199247751b5b18abb52e10f605f4a3f",
        "languageProfileId": "brand-riksmaal",
        "adaptationStatus": "orthography",
        "basedOnEditionId": "kielland-noveletter.original",
        "basedOnContentHash": "sha256:b7d0ef61833c3045e4a5f36a5f46e89e5b867e2ecfe3a672b24d14c6d96a97b7",
        "segmentCount": 13,
        "wordCount": 853,
        "file": "/content/editions/kielland-noveletter.training.v2.e492070c9614.json"
      },
      {
        "id": "kielland-noveletter.training.v3",
        "workId": "kielland-noveletter",
        "kind": "training-edition",
        "version": "3.0.0",
        "contentHash": "sha256:6f32ade3995123227510d9c9e878a46cc9831790d18ba90b4361a561052c6763",
        "languageProfileId": "brand-riksmaal",
        "adaptationStatus": "orthography",
        "basedOnEditionId": "kielland-noveletter.original.v2",
        "basedOnContentHash": "sha256:94b143e16d5cb3aa0ffd7c0efafc447327d4d46a05ae038ffaeac60c77b5f0cc",
        "segmentCount": 264,
        "wordCount": 25669,
        "file": "/content/editions/kielland-noveletter.training.v3.6f32ade39951.json"
      }
    ]
  }
];

export const SHELVES: Shelf[] = [
  {
    "id": "norske-klassikere",
    "title": "Norske klassikere",
    "description": "Ibsen, Hamsun, Kielland, Undset, Lie, Collett og beslektede forfattere.",
    "workIds": [
      "ibsen-brand",
      "hamsun-markens-groede",
      "kielland-gift",
      "kielland-noveletter",
      "hamsun-sult"
    ]
  },
  {
    "id": "danske-klassikere",
    "title": "Danske klassikere",
    "description": "Bang, Pontoppidan, Jacobsen, Holberg og beslektede forfattere.",
    "workIds": []
  },
  {
    "id": "ide-og-tro",
    "title": "Idé og tro",
    "description": "Kierkegaard, Grundtvig, Georg Brandes og andre filosofiske, teologiske eller idéhistoriske tekster.",
    "workIds": []
  },
  {
    "id": "korte-tekster",
    "title": "Korte tekster",
    "description": "Noveller, essays, taler, utdrag og utvalgte eventyr — egnet for korte økter.",
    "workIds": [
      "kielland-noveletter"
    ]
  }
];
