/**
 * GENERATED by `pnpm build:content` — do not edit.
 *
 * Packs, works and edition headers. No segment text: that lives in
 * `public/content/editions/` and is fetched per edition, so the bundle does
 * not grow with the corpus.
 */
import type { ContentPack, Work } from "../types";

export const CONTENT_PACKS: ContentPack[] = [
  {
    "id": "hamsun-markens-groede",
    "title": "Knut Hamsun: Markens grøde",
    "description": "Langform, naturprosa og vedvarende rytme. V1 rommer åpningen av første del, kapittel I (1917).",
    "languageProfileIds": [
      "brand-riksmaal"
    ],
    "workIds": [
      "hamsun-markens-groede"
    ],
    "tags": [
      "prosa",
      "roman",
      "1900-tallet"
    ],
    "status": "active",
    "sourceAttribution": [
      {
        "author": "Knut Hamsun",
        "title": "Markens Grøde",
        "publishedYear": 1917,
        "language": "da-NO",
        "sourceUrl": "https://no.wikisource.org/wiki/Markens_Gr%C3%B8de/1/01",
        "archiveId": "wikikilden:Markens_Grøde/1/01",
        "retrievedAt": "2026-09-04",
        "provider": "Wikikilden (no.wikisource.org)",
        "license": "Public domain i Norge (Hamsun d. 1952; verkets vernetid utløp 2023-01-01, life+70) og i USA (utgitt 1917, før 1928-grensen). Wikikildens transkripsjon er en tro gjengivelse av en offentlig tekst og tilbys under CC BY-SA 4.0; attribusjon til Wikikilden er beholdt her.",
        "digitalEdition": "Markens Grøde. Kristiania: Gyldendal, 1917. Første del, kapittel I (transkribert etter Internet Archive-skanningen markensgrde01hams).",
        "verificationStatus": "agent-drafted",
        "editorialNotes": [
          "Rå HTML arkivert under source/wikikilden/markens-groede-1-01.html; ekstrahert tekst i source/markens-groede-1-01.txt."
        ]
      }
    ]
  },
  {
    "id": "ibsen-brand",
    "title": "Henrik Ibsen: Brand",
    "description": "Produktets navngivende kjernetekst. Et dramatisk dikt i fem akter (1866); V1 rommer åpningsscenen i første akt.",
    "languageProfileIds": [
      "brand-riksmaal"
    ],
    "workIds": [
      "ibsen-brand"
    ],
    "tags": [
      "drama",
      "vers",
      "1800-tallet"
    ],
    "status": "active",
    "sourceAttribution": [
      {
        "author": "Henrik Ibsen",
        "title": "Brand. Et dramatisk digt",
        "publishedYear": 1866,
        "language": "da-NO",
        "sourceUrl": "https://runeberg.org/brand/",
        "archiveId": "runeberg:brand",
        "retrievedAt": "2026-09-04",
        "provider": "Project Runeberg",
        "license": "Public domain (Ibsen d. 1906; edition printed 1903). Transcription proofread at least once on Project Runeberg.",
        "digitalEdition": "Brand. Et dramatisk digt. Femtende oplag. København: Gyldendalske Boghandels Forlag (F. Hegel & Søn), 1903. Scanned and OCR-transcribed by Project Runeberg.",
        "verificationStatus": "agent-drafted",
        "editorialNotes": [
          "Pages 3–14 archived under source/runeberg/; extracted text in source/runeberg-brand-0003-0014.txt.",
          "Cross-reference: Henrik Ibsens skrifter (ibsen.uio.no, CC BY-NC 4.0) for the 1866 first-edition text."
        ]
      }
    ]
  },
  {
    "id": "kielland-gift",
    "title": "Alexander Kielland: Gift",
    "description": "Samfunnskritisk roman med variert dialog og fortellende prosa. V1 rommer åpningen av kapittel I (1883/1907-teksten).",
    "languageProfileIds": [
      "brand-riksmaal"
    ],
    "workIds": [
      "kielland-gift"
    ],
    "tags": [
      "prosa",
      "roman",
      "1800-tallet",
      "dialog"
    ],
    "status": "active",
    "sourceAttribution": [
      {
        "author": "Alexander L. Kielland",
        "title": "Gift",
        "publishedYear": 1883,
        "language": "da-NO",
        "sourceUrl": "https://no.wikisource.org/wiki/Gift/1",
        "archiveId": "wikikilden:Gift/1",
        "retrievedAt": "2026-09-04",
        "provider": "Wikikilden (no.wikisource.org)",
        "license": "Public domain (Kielland d. 1906; verkets vernetid er utløpt, life+70). Wikikildens transkripsjon er en tro gjengivelse av en offentlig tekst og tilbys under CC BY-SA 4.0; attribusjon til Wikikilden er beholdt her.",
        "digitalEdition": "Samlede Værker, Andet Bind. Kristiania: Gyldendalske Boghandel Nordisk Forlag, 1907. Gift, kapittel I (trykte sider 165–171).",
        "verificationStatus": "agent-drafted",
        "editorialNotes": [
          "Rå HTML arkivert under source/wikikilden/gift-1.html; ekstrahert tekst i source/gift-1.txt."
        ]
      }
    ]
  },
  {
    "id": "kielland-noveletter",
    "title": "Alexander Kielland: Noveletter",
    "description": "Korte, selvstendige økter. V1 rommer åpningen av to noveller fra samlingen Noveletter (1879): «Haabet er lysegrønt» og «Visne Blade».",
    "languageProfileIds": [
      "brand-riksmaal"
    ],
    "workIds": [
      "kielland-noveletter"
    ],
    "tags": [
      "prosa",
      "novelle",
      "1800-tallet"
    ],
    "status": "active",
    "sourceAttribution": [
      {
        "author": "Alexander L. Kielland",
        "title": "Haabet er lysegrønt",
        "publishedYear": 1879,
        "language": "da-NO",
        "sourceUrl": "https://no.wikisource.org/wiki/Haabet_er_lysegr%C3%B8nt",
        "archiveId": "wikikilden:Haabet_er_lysegrønt",
        "retrievedAt": "2026-09-04",
        "provider": "Wikikilden (no.wikisource.org)",
        "license": "Public domain (Kielland d. 1906; verkets vernetid er utløpt, life+70). Wikikildens transkripsjon er en tro gjengivelse av en offentlig tekst og tilbys under CC BY-SA 4.0; attribusjon til Wikikilden er beholdt her.",
        "digitalEdition": "Samlede Værker, Første Bind. Kristiania: Gyldendalske Boghandel Nordisk Forlag, 1907. «Haabet er lysegrønt» (trykte sider 7–13).",
        "verificationStatus": "agent-drafted",
        "editorialNotes": [
          "Rå HTML arkivert under source/wikikilden/haabet-er-lysegroent.html."
        ]
      },
      {
        "author": "Alexander L. Kielland",
        "title": "Visne Blade",
        "publishedYear": 1879,
        "language": "da-NO",
        "sourceUrl": "https://no.wikisource.org/wiki/Visne_Blade",
        "archiveId": "wikikilden:Visne_Blade",
        "retrievedAt": "2026-09-04",
        "provider": "Wikikilden (no.wikisource.org)",
        "license": "Public domain (Kielland d. 1906; verkets vernetid er utløpt, life+70). Wikikildens transkripsjon er en tro gjengivelse av en offentlig tekst og tilbys under CC BY-SA 4.0; attribusjon til Wikikilden er beholdt her.",
        "digitalEdition": "Samlede Værker, Første Bind. Kristiania: Gyldendalske Boghandel Nordisk Forlag, 1907. «Visne Blade» (trykte sider 13–16).",
        "verificationStatus": "agent-drafted",
        "editorialNotes": [
          "Rå HTML arkivert under source/wikikilden/visne-blade.html.",
          "Novellesamlingens prioriterte tekst, «Ballstemning», har ingen bekreftet fri digital kilde funnet; se docs/CORPUS_STATUS.md."
        ]
      }
    ]
  }
];

export const WORKS: Work[] = [
  {
    "id": "hamsun-markens-groede",
    "contentPackId": "hamsun-markens-groede",
    "author": "Knut Hamsun",
    "title": "Markens grøde",
    "publishedYear": 1917,
    "source": {
      "author": "Knut Hamsun",
      "title": "Markens Grøde",
      "publishedYear": 1917,
      "language": "da-NO",
      "sourceUrl": "https://no.wikisource.org/wiki/Markens_Gr%C3%B8de/1/01",
      "archiveId": "wikikilden:Markens_Grøde/1/01",
      "retrievedAt": "2026-09-04",
      "provider": "Wikikilden (no.wikisource.org)",
      "license": "Public domain i Norge (Hamsun d. 1952; verkets vernetid utløp 2023-01-01, life+70) og i USA (utgitt 1917, før 1928-grensen). Wikikildens transkripsjon er en tro gjengivelse av en offentlig tekst og tilbys under CC BY-SA 4.0; attribusjon til Wikikilden er beholdt her.",
      "digitalEdition": "Markens Grøde. Kristiania: Gyldendal, 1917. Første del, kapittel I (transkribert etter Internet Archive-skanningen markensgrde01hams; Wikikilden-siden Markens_Grøde/1/01 transkluderer sidene 5–15 i skannet bok / trykte sider 11–21).",
      "verificationStatus": "agent-drafted",
      "editorialNotes": [
        "Rå HTML arkivert under source/wikikilden/markens-groede-1-01.html; ekstrahert tekst i source/markens-groede-1-01.txt.",
        "Kapitteloverskriften «I» er ikke tatt med som segment; utdraget starter på kapitlets første prosalinje («Den lange, lange Sti …»)."
      ]
    },
    "editions": [
      {
        "id": "hamsun-markens-groede.original",
        "workId": "hamsun-markens-groede",
        "kind": "original",
        "version": "1.0.0",
        "contentHash": "sha256:db67765fc4831f1266973af04debf38a2ea64493a0b6f430d0a9391a0eb572a2",
        "segmentCount": 8,
        "wordCount": 813,
        "file": "/content/editions/hamsun-markens-groede.original.db67765fc483.json"
      },
      {
        "id": "hamsun-markens-groede.training.v1",
        "workId": "hamsun-markens-groede",
        "kind": "training-edition",
        "version": "1.0.0",
        "contentHash": "sha256:1d8c5519a5afbf1ddee33976cf063627f34f76b2ba12a6a7b33fc0cb52cf69d5",
        "languageProfileId": "brand-riksmaal",
        "basedOnEditionId": "hamsun-markens-groede.original",
        "basedOnContentHash": "sha256:db67765fc4831f1266973af04debf38a2ea64493a0b6f430d0a9391a0eb572a2",
        "segmentCount": 8,
        "wordCount": 813,
        "file": "/content/editions/hamsun-markens-groede.training.v1.1d8c5519a5af.json"
      }
    ]
  },
  {
    "id": "ibsen-brand",
    "contentPackId": "ibsen-brand",
    "author": "Henrik Ibsen",
    "title": "Brand",
    "publishedYear": 1866,
    "source": {
      "author": "Henrik Ibsen",
      "title": "Brand. Et dramatisk digt",
      "publishedYear": 1866,
      "language": "da-NO",
      "sourceUrl": "https://runeberg.org/brand/",
      "archiveId": "runeberg:brand",
      "retrievedAt": "2026-09-04",
      "provider": "Project Runeberg",
      "license": "Public domain (Ibsen d. 1906; edition printed 1903). Transcription proofread at least once on Project Runeberg.",
      "digitalEdition": "Brand. Et dramatisk digt. Femtende oplag. København: Gyldendalske Boghandels Forlag (F. Hegel & Søn), 1903. Pages 7–14 (første akt, åpningen).",
      "verificationStatus": "agent-drafted",
      "editorialNotes": [
        "Transkripsjonen følger Runeberg-teksten ord for ord. Trykkets halvlinje-innrykk (verselinjer delt mellom replikker) er ikke gjengitt; hver replikkdel står på egen linje uten innrykk.",
        "Sidemarkører og blanke linjer fra skanningen er fjernet. Ingen språklige inngrep."
      ]
    },
    "editions": [
      {
        "id": "ibsen-brand.original",
        "workId": "ibsen-brand",
        "kind": "original",
        "version": "1.0.0",
        "contentHash": "sha256:dcca48d310d6dd50dddb91848ffaa169acb4f530d595f017e7198b7db953ac37",
        "segmentCount": 12,
        "wordCount": 931,
        "file": "/content/editions/ibsen-brand.original.dcca48d310d6.json"
      },
      {
        "id": "ibsen-brand.training.v1",
        "workId": "ibsen-brand",
        "kind": "training-edition",
        "version": "1.0.0",
        "contentHash": "sha256:92d613d9b1a385454935b2ce614de39fe1159a77a1569f67393a3cd18e3170e9",
        "languageProfileId": "brand-riksmaal",
        "basedOnEditionId": "ibsen-brand.original",
        "basedOnContentHash": "sha256:dcca48d310d6dd50dddb91848ffaa169acb4f530d595f017e7198b7db953ac37",
        "segmentCount": 12,
        "wordCount": 936,
        "file": "/content/editions/ibsen-brand.training.v1.92d613d9b1a3.json"
      }
    ]
  },
  {
    "id": "kielland-gift",
    "contentPackId": "kielland-gift",
    "author": "Alexander L. Kielland",
    "title": "Gift",
    "publishedYear": 1883,
    "source": {
      "author": "Alexander L. Kielland",
      "title": "Gift",
      "publishedYear": 1883,
      "language": "da-NO",
      "sourceUrl": "https://no.wikisource.org/wiki/Gift/1",
      "archiveId": "wikikilden:Gift/1",
      "retrievedAt": "2026-09-04",
      "provider": "Wikikilden (no.wikisource.org)",
      "license": "Public domain (Kielland d. 1906; verkets vernetid er utløpt, life+70). Wikikildens transkripsjon er en tro gjengivelse av en offentlig tekst og tilbys under CC BY-SA 4.0; attribusjon til Wikikilden er beholdt her. Wikikilden-siden merker kilden {{PD-old|nb}}.",
      "digitalEdition": "Samlede Værker, Andet Bind. Kristiania: Gyldendalske Boghandel Nordisk Forlag, 1907. Gift, kapittel I (trykte sider 165–171).",
      "verificationStatus": "agent-drafted",
      "editorialNotes": [
        "Rå HTML arkivert under source/wikikilden/gift-1.html; ekstrahert tekst i source/gift-1.txt.",
        "Gift ble første gang utgitt 1883; teksten her følger 1907-utgaven i Samlede Værker slik den er transkribert på Wikikilden."
      ]
    },
    "editions": [
      {
        "id": "kielland-gift.original",
        "workId": "kielland-gift",
        "kind": "original",
        "version": "1.0.0",
        "contentHash": "sha256:2dff6f05866e1f32ef3c4403a73bd9f268d580f90263c022607f294c2374bfa9",
        "segmentCount": 13,
        "wordCount": 855,
        "file": "/content/editions/kielland-gift.original.2dff6f05866e.json"
      },
      {
        "id": "kielland-gift.training.v1",
        "workId": "kielland-gift",
        "kind": "training-edition",
        "version": "1.0.0",
        "contentHash": "sha256:2365ad52a5d090f7c8460276810c68ba65f08329f84b3835bd7ae6d6e057772a",
        "languageProfileId": "brand-riksmaal",
        "basedOnEditionId": "kielland-gift.original",
        "basedOnContentHash": "sha256:2dff6f05866e1f32ef3c4403a73bd9f268d580f90263c022607f294c2374bfa9",
        "segmentCount": 13,
        "wordCount": 858,
        "file": "/content/editions/kielland-gift.training.v1.2365ad52a5d0.json"
      }
    ]
  },
  {
    "id": "kielland-noveletter",
    "contentPackId": "kielland-noveletter",
    "author": "Alexander L. Kielland",
    "title": "Noveletter",
    "publishedYear": 1879,
    "source": {
      "author": "Alexander L. Kielland",
      "title": "Noveletter",
      "publishedYear": 1879,
      "language": "da-NO",
      "sourceUrl": "https://no.wikisource.org/wiki/Novelletter",
      "archiveId": "wikikilden:Novelletter",
      "retrievedAt": "2026-09-04",
      "provider": "Wikikilden (no.wikisource.org)",
      "license": "Public domain (Kielland d. 1906; verkets vernetid er utløpt, life+70). Wikikildens transkripsjon er en tro gjengivelse av en offentlig tekst og tilbys under CC BY-SA 4.0; attribusjon til Wikikilden er beholdt her.",
      "digitalEdition": "Samlede Værker, Første Bind. Kristiania: Gyldendalske Boghandel Nordisk Forlag, 1907. To noveller er brukt: «Haabet er lysegrønt» (trykte sider 7–13, Wikikilden-siden Haabet_er_lysegrønt) og «Visne Blade» (trykte sider 13–16, Wikikilden-siden Visne_Blade). Åpningen av hver novelle er tatt med.",
      "verificationStatus": "agent-drafted",
      "editorialNotes": [
        "Rå HTML arkivert under source/wikikilden/haabet-er-lysegroent.html og source/wikikilden/visne-blade.html; hver novelle er ekstrahert til sin egen .txt og deretter satt sammen til source/noveletter.txt (Haabet er lysegrønt først, så Visne Blade), fordi segments.json/build-original.ts bare støtter én sourceFile per pakke.",
        "«Ballstemning», som er spesifikasjonens prioriterte novelle, har ingen bekreftet fri digital kilde funnet (Wikikilden: 0 treff i søk på tittelen; Project Gutenberg: bare oversettelser; runeberg.org: kielsaml/kinovel-katalogsidene svarer 404). «Visne Blade» er brukt i stedet; se docs/CORPUS_STATUS.md for detaljer om forsøket."
      ]
    },
    "editions": [
      {
        "id": "kielland-noveletter.original",
        "workId": "kielland-noveletter",
        "kind": "original",
        "version": "1.0.0",
        "contentHash": "sha256:b7d0ef61833c3045e4a5f36a5f46e89e5b867e2ecfe3a672b24d14c6d96a97b7",
        "segmentCount": 13,
        "wordCount": 851,
        "file": "/content/editions/kielland-noveletter.original.b7d0ef61833c.json"
      },
      {
        "id": "kielland-noveletter.training.v1",
        "workId": "kielland-noveletter",
        "kind": "training-edition",
        "version": "1.0.0",
        "contentHash": "sha256:3fc4e8c12212d5e63a450cb13698574b6df43343bd8b01c08e377352113b64bc",
        "languageProfileId": "brand-riksmaal",
        "basedOnEditionId": "kielland-noveletter.original",
        "basedOnContentHash": "sha256:b7d0ef61833c3045e4a5f36a5f46e89e5b867e2ecfe3a672b24d14c6d96a97b7",
        "segmentCount": 13,
        "wordCount": 853,
        "file": "/content/editions/kielland-noveletter.training.v1.3fc4e8c12212.json"
      }
    ]
  }
];
